/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.staging.jsonc --include-runtime=false --strict-vars=false workers/platform/env.d.ts` (hash: 06434f30ccc9ec5eab0fcd383de87f17)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	WEATHER_ENABLED: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
