name = "grace-vrcc"
main = "index.js"
compatibility_date = "2025-07-10"
account_id = "499272c2f0336cc60207bad24edd0e14"

[vars]
PLATFORM = "GFA Recovery OS"
VERSION = "6.0"

[[routes]]
pattern = "vrcc.app/*"
zone_name = "vrcc.app"
