export type ResourceCategory = 'Recovery & connection' | 'Housing & essentials' | 'Work & benefits' | 'Legal help' | 'Support now' | 'Reentry' | 'Online meetings' | 'Healthcare' | 'Harm reduction';

export type CommunityResource = {
  id: string;
  name: string;
  category: ResourceCategory;
  description: string;
  href: string;
  action: string;
  external: boolean;
  keywords: string;
};

export const resourceCategories: ResourceCategory[] = [
  'Recovery & connection', 'Housing & essentials', 'Work & benefits', 'Legal help', 'Support now', 'Reentry', 'Online meetings', 'Healthcare', 'Harm reduction',
];

// Public navigation only: provider websites remain the authority for eligibility,
// hours, schedules, and availability. External source pages reviewed 2026-10-05.
export const communityResources: CommunityResource[] = [
  { id: 'gfa-peer', name: 'GFA peer support', category: 'Recovery & connection', description: 'Start at the front desk for the GFA Warmline and help choosing a next step.', href: '/community-center/front-desk', action: 'Visit the front desk', external: false, keywords: 'coach warmline talk person peer' },
  { id: 'recovery-iowa', name: 'Recovery Iowa', category: 'Recovery & connection', description: 'Explore Iowa recovery resources, support networks, and educational tools through Recovery Iowa’s existing directory.', href: 'https://recovery-iowa.org/get-support/', action: 'Explore Recovery Iowa', external: true, keywords: 'statewide map recovery community center meeting peer substance use' },
  { id: 'nami', name: 'NAMI Iowa support groups', category: 'Recovery & connection', description: 'Find mental health support group information for individuals and families. Check the provider for current meeting details.', href: 'https://namiiowa.org/support-and-education/support-groups/', action: 'Find support groups', external: true, keywords: 'family mental health belonging group' },
  { id: 'housing', name: 'Recovery housing in RecoveryOS', category: 'Housing & essentials', description: 'Explore Grace House and Ernest & Johnnie White Recovery House information and application paths.', href: '/recovery-residences', action: 'Explore recovery housing', external: false, keywords: 'residence grace house ejwrh application home' },
  { id: '211', name: 'Iowa 211 resource search', category: 'Housing & essentials', description: 'Search local resources for food, shelter, utilities, transportation, and other practical needs by location.', href: 'https://search.211iowa.org/', action: 'Search Iowa 211', external: true, keywords: 'food pantry rent shelter utilities transportation child care reentry' },
  { id: 'iowaworks', name: 'IowaWORKS', category: 'Work & benefits', description: 'Find IowaWORKS centers for job search, career assistance, training connections, and employment services.', href: 'https://workforce.iowa.gov/jobs/iowaworks', action: 'Find employment support', external: true, keywords: 'job resume interview career training unemployment work' },
  { id: 'hhs', name: 'Iowa HHS assistance programs', category: 'Work & benefits', description: 'Learn how to check eligibility and apply for food assistance, health coverage, and other Iowa HHS services.', href: 'https://hhs.iowa.gov/assistance-programs/apply', action: 'Explore assistance programs', external: true, keywords: 'snap food medicaid benefits child care insurance' },
  { id: 'legal', name: 'Iowa Legal Aid', category: 'Legal help', description: 'Find civil legal information and ways to request legal help, including housing and family matters. Eligibility is determined by Iowa Legal Aid.', href: 'https://iowalegalaid.org/', action: 'Explore legal help', external: true, keywords: 'eviction landlord rights family civil legal' },
  { id: 'support', name: 'RecoveryOS Support Now', category: 'Support now', description: 'Open immediate support options, including crisis and warmline contacts, without an account.', href: '/support', action: 'Open Support Now', external: false, keywords: '988 911 crisis urgent safety warmline' },
  { id: 'yli', name: 'Your Life Iowa', category: 'Support now', description: 'Find 24/7 support and information for alcohol, drugs, gambling, mental health, and concerns about a loved one.', href: 'https://yourlifeiowa.org/', action: 'Visit Your Life Iowa', external: true, keywords: 'family mental health gambling substance use help navigation' },
  {"id":"reentry-guide","name":"Living Beyond the Bars — First Stop After Prison","category":"Reentry","description":"Statewide reentry resource guide organized by Iowa judicial district, with community starting points and planning information.","href":"https://www.livingbeyondthebars.org/reentry","action":"Read the reentry guide","external":true,"keywords":"prison release returning citizen mentoring statewide guide"},
  {"id":"inside-out","name":"Inside Out Reentry Community","category":"Reentry","description":"Iowa City-based reentry planning, mentoring, and practical support for people returning to Johnson County after incarceration.","href":"https://www.insideoutreentry.com/","action":"Explore Inside Out","external":true,"keywords":"johnson county iowa city prison release mentoring"},
  {"id":"svdp","name":"St. Vincent de Paul of Des Moines","category":"Housing & essentials","description":"Explore Des Moines-area food, clothing, education, employment, and other assistance programs.","href":"https://www.svdpdsm.org/","action":"Explore local assistance","external":true,"keywords":"des moines polk food clothing education work reentry"},
  {"id":"full-circle","name":"Full Circle Recovery","category":"Recovery & connection","description":"Find recovery community center locations and peer support programs through one provider website.","href":"https://recoverfullcircle.org/","action":"Explore Full Circle","external":true,"keywords":"des moines council bluffs ankeny neola peer recovery corrections"},
  {"id":"crush","name":"CRUSH of Iowa","category":"Recovery & connection","description":"Explore Cedar Rapids-based recovery community support, events, and telephone recovery support.","href":"https://www.crushofiowa.com/","action":"Explore CRUSH","external":true,"keywords":"cedar rapids linn peer community harm reduction"},
  {"id":"rise","name":"RiSE Recovery Center","category":"Recovery & connection","description":"Explore Des Moines-based recovery coaching, community programs, and events.","href":"https://www.riseiowa.org/","action":"Explore RiSE","external":true,"keywords":"des moines polk coaching community"},
  {"id":"ors","name":"Iowa Office of Recovery Services","category":"Recovery & connection","description":"Find help navigating Iowa mental health and substance use systems, with self-advocacy resources.","href":"https://orsiowa.org/","action":"Explore navigation and advocacy","external":true,"keywords":"statewide rights advocacy mental health substance use"},
  {"id":"hrsa","name":"HRSA Find a Health Center","category":"Healthcare","description":"Search federally supported health centers by city, state, or ZIP code. Contact the center about services and payment options.","href":"https://findahealthcenter.hrsa.gov/","action":"Find a health center","external":true,"keywords":"medical dental primary care clinic insurance rural statewide"},
  {"id":"phc","name":"Primary Health Care","category":"Healthcare","description":"Explore medical, dental, behavioral health, pharmacy, and support services at this Iowa healthcare provider.","href":"https://phciowa.org/","action":"Explore Primary Health Care","external":true,"keywords":"des moines ames marshalltown clinic dental medical health"},
  {"id":"ihrc","name":"Iowa Harm Reduction Coalition","category":"Harm reduction","description":"Find overdose prevention education, naloxone access information, and harm reduction services. Confirm current access with the provider.","href":"https://www.iowaharmreductioncoalition.org/services/","action":"Explore harm reduction services","external":true,"keywords":"naloxone narcan overdose safer use testing"},
  {"id":"aa-online","name":"Alcoholics Anonymous — Online Intergroup","category":"Online meetings","description":"Search online AA meeting listings. Review each meeting’s format, access details, and time zone.","href":"https://aa-intergroup.org/meetings/","action":"Find online AA meetings","external":true,"keywords":"alcohol twelve step 12 step online virtual"},
  {"id":"na-online","name":"Narcotics Anonymous — Virtual Meeting Finder","category":"Online meetings","description":"Use NA World Services’ directory to find virtual NA meetings and access details.","href":"https://na.org/meetingsearch/virtual-meeting-search/","action":"Find virtual NA meetings","external":true,"keywords":"drug substance twelve step 12 step online"},
  {"id":"smart","name":"SMART Recovery","category":"Online meetings","description":"Find online and in-person SMART Recovery meetings offering a self-management approach to recovery.","href":"https://meetings.smartrecovery.org/meetings/","action":"Find SMART meetings","external":true,"keywords":"secular self management family friends online virtual"},
  {"id":"dharma","name":"Recovery Dharma","category":"Online meetings","description":"Find Buddhist-inspired recovery meetings with meditation and peer connection.","href":"https://recoverydharma.org/meetings/","action":"Find Recovery Dharma meetings","external":true,"keywords":"mindfulness meditation buddhist online virtual"},
  {"id":"lifering","name":"LifeRing Secular Recovery","category":"Online meetings","description":"Explore online meetings offering a secular, self-help recovery pathway.","href":"https://lifering.org/meeting-menu/online-meetings/","action":"Find LifeRing meetings","external":true,"keywords":"secular self help non religious online virtual"},
  {"id":"she-recovers","name":"SHE RECOVERS Together Online","category":"Online meetings","description":"Explore women-centered online recovery gatherings and identity-based support options. Check participation guidance on the provider’s site.","href":"https://sherecovers.org/together-online/","action":"Explore SHE RECOVERS","external":true,"keywords":"women nonbinary lgbtq trauma online virtual"},
  {"id":"ma","name":"Marijuana Anonymous","category":"Online meetings","description":"Find online and in-person meetings for people seeking recovery from cannabis use.","href":"https://marijuana-anonymous.org/find-a-meeting/","action":"Find MA meetings","external":true,"keywords":"cannabis marijuana twelve step online virtual"},
  {"id":"dra","name":"Dual Recovery Anonymous","category":"Online meetings","description":"Find peer self-help meetings for people managing substance use recovery and co-occurring mental health concerns.","href":"https://draonline.org/meetings/","action":"Find DRA meetings","external":true,"keywords":"dual diagnosis co occurring mental health twelve step online virtual"},
  {"id":"itr","name":"In The Rooms","category":"Online meetings","description":"Explore a platform hosting online recovery meetings across fellowships. Some participation requires a provider account.","href":"https://www.intherooms.com/home/","action":"Explore In The Rooms","external":true,"keywords":"multi pathway fellowship online virtual account"},
  {"id":"al-anon","name":"Al-Anon and Alateen","category":"Online meetings","description":"Find family and friend support meetings for those affected by someone else’s drinking, including online options.","href":"https://al-anon.org/al-anon-meetings/","action":"Find family support meetings","external":true,"keywords":"family friends loved one youth teen alcohol online"},
];
