/**
 * Iowa recovery-residence directory listings (public page — no auth, no DB).
 * External organizations are compiled from public sources and operator
 * submissions; inclusion is not an endorsement, and details change — always
 * verify directly. GFA residences carry `apply` links into their own
 * application flows.
 */
export type ResidenceListing = {
  name: string;
  org: string;
  city: string;
  county: string;
  population: string;
  type: string;
  contact: string;
  description: string;
  /** External application/information site (GFA residences). */
  applyUrl?: string;
  /** In-app profile route (GFA residences). */
  profilePath?: string;
};

export const GFA_RESIDENCES: ResidenceListing[] = [
  {
    name: 'Grace House',
    org: 'Grace For Addictions',
    city: 'Des Moines',
    county: 'Polk',
    population: 'Women',
    type: 'Nonprofit · Preparing for NARR Level II certification',
    contact: '515-220-8771 · gracehouse@graceforaddictions.org',
    description:
      "Women's recovery residence operated by Grace For Addictions. Phased program, life & recovery coaching, MAT/MOUD-affirming, all pathways honored.",
    applyUrl: 'https://gracehouse4.pages.dev/',
    profilePath: '/recovery-residences/grace-house',
  },
  {
    name: 'Ernest & Johnnie White Recovery House',
    org: 'EJWRH · supported by Grace For Addictions',
    city: 'Des Moines',
    county: 'Polk',
    population: 'Men',
    type: 'Peer-led · Iowa DOC approved',
    contact: '515-220-8771 · ejwrh@rcoiowa.org',
    description:
      "Men's recovery residence with wraparound recovery support services; Iowa DOC approved placement.",
    applyUrl: 'https://cqcxvwoukyhxyokfwnjm.supabase.co/functions/v1/ejwrh',
  },
  {
    name: "Jerry's House",
    org: 'Grace For Addictions',
    city: 'Des Moines',
    county: 'Polk',
    population: 'Men',
    type: 'Nonprofit · Coming soon',
    contact: '515-220-8771',
    description: "Future men's residence honoring Jerry Anderson's open door.",
  },
];

export const IOWA_LISTINGS: ResidenceListing[] = [
  {
    name: 'Beacon of Life',
    org: 'Beacon of Life',
    city: 'Des Moines',
    county: 'Polk',
    population: 'Women',
    type: 'Nonprofit recovery housing',
    contact: '515-244-4713 · beaconoflifedsm.org',
    description:
      "Long-standing Des Moines women's recovery residence offering structured programming and transitional support.",
  },
  {
    name: 'House of Mercy',
    org: 'MercyOne',
    city: 'Des Moines',
    county: 'Polk',
    population: 'Women & children',
    type: 'Nonprofit · treatment-affiliated housing',
    contact: '515-643-6500',
    description: 'Supportive housing for women and their children alongside recovery services.',
  },
  {
    name: 'Bridges of Iowa',
    org: 'Bridges of Iowa',
    city: 'Des Moines',
    county: 'Polk',
    population: 'Men',
    type: 'Nonprofit long-term recovery program',
    contact: '515-263-9030 · bridgesofiowa.org',
    description: 'Long-term residential recovery program with employment and life-skills pathway.',
  },
  {
    name: 'Hope Ministries — Door of Faith',
    org: 'Hope Ministries',
    city: 'Des Moines',
    county: 'Polk',
    population: 'Men',
    type: 'Faith-based recovery residence',
    contact: '515-265-7272 · hopeiowa.org',
    description: "Faith-based men's recovery and life-recovery program.",
  },
  {
    name: 'Hope Ministries — Hope Center for Women & Children',
    org: 'Hope Ministries',
    city: 'Des Moines',
    county: 'Polk',
    population: 'Women & children',
    type: 'Faith-based recovery residence',
    contact: '515-265-7272 · hopeiowa.org',
    description: 'Faith-based recovery and housing for women and children.',
  },
  {
    name: 'Kingdom Living Iowa',
    org: 'Kingdom Living',
    city: 'Des Moines',
    county: 'Polk',
    population: 'All genders',
    type: 'Structured recovery housing',
    contact: '4000 SW 9th St, Des Moines',
    description:
      'Structured substance-free housing; double $110/wk, single $135/wk (verify current rates).',
  },
  {
    name: 'Oxford House network — Des Moines',
    org: 'Oxford House, Inc.',
    city: 'Des Moines',
    county: 'Polk',
    population: 'All genders',
    type: 'Peer-run · democratically governed (7 houses)',
    contact: 'oxfordvacancies.com',
    description:
      "Seven chartered Oxford Houses across the Des Moines metro (incl. 1801 Hickman Rd). Self-run, self-supporting, substance-free homes; houses are single-gender — men's and women's houses available.",
  },
  {
    name: 'Clearview Recovery',
    org: 'Clearview Recovery Inc.',
    city: 'Prairie City',
    county: 'Jasper',
    population: 'Women',
    type: 'Nonprofit recovery residence',
    contact: '515-994-2650 · clearviewrecovery.org',
    description: "Rural women's recovery residence east of Des Moines with structured programming.",
  },
  {
    name: 'Adult & Teen Challenge of the Midlands',
    org: 'Adult & Teen Challenge',
    city: 'Colfax',
    county: 'Jasper',
    population: 'Men',
    type: 'Faith-based residential recovery',
    contact: '515-674-3713',
    description: 'Long-term faith-based residential recovery campus.',
  },
  {
    name: 'Oxford House network — Cedar Rapids',
    org: 'Oxford House, Inc.',
    city: 'Cedar Rapids',
    county: 'Linn',
    population: 'All genders',
    type: 'Peer-run · democratically governed (5 houses)',
    contact: 'oxfordvacancies.com',
    description:
      'Five chartered Oxford Houses (incl. 3601 16th Ave SW). Single-gender houses; contact for current vacancies.',
  },
  {
    name: 'Oxford House network — Davenport',
    org: 'Oxford House, Inc.',
    city: 'Davenport',
    county: 'Scott',
    population: 'All genders',
    type: 'Peer-run · democratically governed (3 houses)',
    contact: 'oxfordvacancies.com',
    description: 'Three chartered Oxford Houses (incl. 1523 S Fairmount St).',
  },
  {
    name: 'One Eighty Sober Living',
    org: 'One Eighty',
    city: 'Davenport',
    county: 'Scott',
    population: 'All genders',
    type: 'Faith-based recovery community',
    contact: '563-424-1961 · one-eighty.org',
    description:
      'Faith-based recovery community offering substance-free homes and recovery programming in the Quad Cities.',
  },
  {
    name: 'Oxford House 16th Street',
    org: 'Oxford House, Inc.',
    city: 'Sioux City',
    county: 'Woodbury',
    population: 'All genders',
    type: 'Peer-run',
    contact: '712-560-4134 · 209 16th St',
    description:
      'Self-run, self-supporting substance-free home (verify current charter/population).',
  },
  {
    name: 'Oxford House Douglas Street',
    org: 'Oxford House, Inc.',
    city: 'Sioux City',
    county: 'Woodbury',
    population: 'Men',
    type: 'Peer-run',
    contact: '712-560-8351 · 2615 Douglas St',
    description: "Men's Oxford House — democratically run, self-supporting, substance-free.",
  },
  {
    name: 'Oxford House Nebraska Street',
    org: 'Oxford House, Inc.',
    city: 'Sioux City',
    county: 'Woodbury',
    population: 'Women',
    type: 'Peer-run',
    contact: '712-224-4546 · 2931 Nebraska St',
    description: "Women's Oxford House — democratically run, self-supporting, substance-free.",
  },
  {
    name: 'Rosecrance Jackson Centers — Recovery Housing',
    org: 'Rosecrance',
    city: 'Sioux City',
    county: 'Woodbury',
    population: 'All genders',
    type: 'Treatment-affiliated recovery housing',
    contact: '712-234-2300 · rosecrance.org',
    description: 'Recovery-supportive housing connected to Rosecrance Jackson Centers continuum.',
  },
  {
    name: 'Oxford House Loess Hills',
    org: 'Oxford House, Inc.',
    city: 'Council Bluffs',
    county: 'Pottawattamie',
    population: 'Women & children',
    type: 'Peer-run',
    contact: '712-256-1954 · 200 S 1st St',
    description: 'Women & children Oxford House — residents govern the home democratically.',
  },
  {
    name: 'Oxford House network — Council Bluffs',
    org: 'Oxford House, Inc.',
    city: 'Council Bluffs',
    county: 'Pottawattamie',
    population: 'All genders',
    type: 'Peer-run (3 houses citywide)',
    contact: 'oxfordvacancies.com',
    description: 'Three chartered houses citywide including Loess Hills and Bayliss Park.',
  },
  {
    name: 'Oxford House network — Waterloo',
    org: 'Oxford House, Inc.',
    city: 'Waterloo',
    county: 'Black Hawk',
    population: 'All genders',
    type: 'Peer-run (2 houses)',
    contact: 'oxfordvacancies.com',
    description: 'Two chartered Oxford Houses serving the Cedar Valley.',
  },
  {
    name: 'Oxford House — Iowa City',
    org: 'Oxford House, Inc.',
    city: 'Iowa City',
    county: 'Johnson',
    population: 'All genders',
    type: 'Peer-run',
    contact: '438 Southgate Ave · oxfordvacancies.com',
    description: 'Chartered Oxford House serving Johnson County.',
  },
  {
    name: 'Cedar River Haven',
    org: 'Cedar River Haven',
    city: 'Letts',
    county: 'Muscatine',
    population: 'Women',
    type: 'Nonprofit · 24-bed rural transitional',
    contact: '319-726-2360',
    description:
      "Rural women's recovery community: safe shelter, employment support, community, and life skills.",
  },
  {
    name: 'Oxford House network — Clinton',
    org: 'Oxford House, Inc.',
    city: 'Clinton',
    county: 'Clinton',
    population: 'All genders',
    type: 'Peer-run (2 houses)',
    contact: '2727 & 2733 S 19th St · oxfordvacancies.com',
    description: 'Two chartered Oxford Houses on South 19th Street.',
  },
  {
    name: 'Oxford House — Burlington',
    org: 'Oxford House, Inc.',
    city: 'Burlington',
    county: 'Des Moines Co.',
    population: 'All genders',
    type: 'Peer-run',
    contact: '1340 Mount Pleasant St · oxfordvacancies.com',
    description: 'Chartered Oxford House serving southeast Iowa.',
  },
  {
    name: 'Oxford House — Dubuque',
    org: 'Oxford House, Inc.',
    city: 'Dubuque',
    county: 'Dubuque',
    population: 'All genders',
    type: 'Peer-run',
    contact: 'oxfordvacancies.com',
    description: 'Chartered Oxford House serving Dubuque.',
  },
  {
    name: 'Oxford House — Fort Dodge',
    org: 'Oxford House, Inc.',
    city: 'Fort Dodge',
    county: 'Webster',
    population: 'All genders',
    type: 'Peer-run',
    contact: 'oxfordvacancies.com',
    description: 'Chartered Oxford House serving Webster County.',
  },
  {
    name: 'Oxford House — Mason City',
    org: 'Oxford House, Inc.',
    city: 'Mason City',
    county: 'Cerro Gordo',
    population: 'All genders',
    type: 'Peer-run',
    contact: 'oxfordvacancies.com',
    description: 'Chartered Oxford House serving north-central Iowa.',
  },
  {
    name: 'Oxford House — Osceola',
    org: 'Oxford House, Inc.',
    city: 'Osceola',
    county: 'Clarke',
    population: 'All genders',
    type: 'Peer-run',
    contact: 'oxfordvacancies.com',
    description: 'Chartered Oxford House serving Clarke County.',
  },
  {
    name: 'Oxford House — Oskaloosa',
    org: 'Oxford House, Inc.',
    city: 'Oskaloosa',
    county: 'Mahaska',
    population: 'All genders',
    type: 'Peer-run',
    contact: 'oxfordvacancies.com',
    description: 'Chartered Oxford House serving Mahaska County.',
  },
  {
    name: 'Oxford House network — Ottumwa',
    org: 'Oxford House, Inc.',
    city: 'Ottumwa',
    county: 'Wapello',
    population: 'All genders',
    type: 'Peer-run (2 houses)',
    contact: 'oxfordvacancies.com',
    description: 'Two chartered Oxford Houses serving Wapello County.',
  },
  {
    name: 'Oxford House — Waverly',
    org: 'Oxford House, Inc.',
    city: 'Waverly',
    county: 'Bremer',
    population: 'All genders',
    type: 'Peer-run',
    contact: 'oxfordvacancies.com',
    description: 'Chartered Oxford House serving Bremer County.',
  },
];
