-- 0146_ejwrh_document_activation.sql — EJWRH document edition activation.
--
-- Generated by scripts/build-ejwrh-activation.mjs (effective 2026-08-31) from the
-- canonical edition files in docs/residences/ejwrh/ — bodies are never hand-transcribed.
--
-- AUTHORITY: five acknowledgment editions executive-ratified 2026-08-24 (frozen hashes);
-- Participant & Residency Agreement executively approved 2026-08-31 with PSA v4.1
-- execution attested by the Executive Director and the counterparty named operatively
-- (Ernest & Johnnie White Recovery House, L.L.C.); e-sign legal review APPROVED WITH
-- ATTACHED REVISIONS 2026-08-24 (e-consent gate + paper parity live via 0145).
-- The record-retention period remains an open records-policy item: no period is asserted
-- in any seeded text; signed artifacts are preserved immutably and indefinitely pending it.
--
-- ON APPLY: EJWRH (residence 2) readiness flips from the single non-overridable
-- 'pending_document_edition' placeholder to the real 1-signature + 5-acknowledgment set;
-- ensure_my_document_assignments starts assigning at residence 2 with no code change.
--
-- ROLLBACK (reversible without deleting evidence):
--   update recoveryos.document_versions dv set published_at = null
--     from recoveryos.document_templates t
--     where t.id = dv.template_id and t.key like 'ejwrh_%'
--       and not exists (select 1 from recoveryos.document_assignments a
--                       where a.document_version_id = dv.id);
--   update recoveryos.document_templates set is_active = false where key like 'ejwrh_%';
--   (Versions already carrying assignments are immutable evidence — never unpublished.)

set search_path = recoveryos, public;

-- 1) Templates: EJWRH-scoped (residence 2), 1 signature + 5 acknowledgments. Idempotent.
insert into recoveryos.document_templates
  (organization_id, key, name, is_active, requires_signature, requires_acknowledgment, residence_id)
select o.id, v.key, v.name, true, v.sig, v.ack, 2
from (values
  ('ejwrh_participant_agreement', 'EJWRH Participant & Residency Agreement', true, false),
  ('ejwrh_resident_handbook', 'EJWRH Resident Handbook', false, true),
  ('ejwrh_resident_rights_grievance', 'EJWRH Resident Rights & Grievance', false, true),
  ('ejwrh_screening_policy', 'EJWRH Screening Policy', false, true),
  ('ejwrh_medication_moud_policy', 'EJWRH Medication & MOUD Policy', false, true),
  ('ejwrh_return_to_use_response_policy', 'EJWRH Return-to-Use Response Policy', false, true)
) as v(key, name, sig, ack)
cross join (select id from recoveryos.organizations where name = 'Grace For Addictions') o
on conflict (organization_id, key) do update set
  name = excluded.name, is_active = excluded.is_active,
  requires_signature = excluded.requires_signature,
  requires_acknowledgment = excluded.requires_acknowledgment,
  residence_id = excluded.residence_id;

-- 2) Versions: v1.0 published at the executive effective date.
insert into recoveryos.document_versions (template_id, version, body_markdown, published_at)
select t.id, '1.0', $ejwrh_body$# EJWRH Participant & Residency Agreement

Ernest & Johnnie White Recovery House · 1414 12th Street, Des Moines, Iowa 50314
Office: 515-220-8771 · ejwrh@rcoiowa.org

> **About this agreement.** This is a program participation agreement, not a residential
> lease. It is the one document you sign to live at EJWRH. Read it carefully, and ask
> questions about anything unclear before signing — asking first is exactly what intake is
> for. Signing is a mutual commitment: the house commits to you as you commit to the house.
> **Nothing in this agreement waives your rights as a resident.**

This agreement references the following documents, which you will review and acknowledge —
they explain, they do not add hidden contract terms: the **Resident Handbook**, the
**Resident Rights & Grievance Process**, the **Screening Policy**, the **Medication & MOUD
Policy**, and the **Return-to-Use Response Policy**.

## 1. Who we are and what you can expect

EJWRH is a recovery residence. The residence operator holds the housing side of this
agreement — housing operations, resident agreements, financial management, staffing, property,
and housing compliance. Grace For Addictions provides the contracted recovery-support side —
peer coaching, recovery navigation, recovery planning, program development, and the RecoveryOS
platform — and does not manage resident funds. The residence is pursuing NARR Level II
certification through the Iowa affiliate (MCRSP).

This agreement is between you and **Ernest & Johnnie White Recovery House, L.L.C.** — the
residence operator and your contracting party for housing and residency. Grace For
Addictions is the contracted recovery-support, program, and technical service provider —
not the housing contracting party.

You can expect: a safe, alcohol- and illicit-drug-free home; respect and dignity without
regard to your recovery pathway; staff and peers who walk beside you; and honest, documented
decisions — never automated ones — about anything that affects your residency.

## 2. Your residency

- Residency begins on your admission date and continues while you participate in the program
  and meet the commitments in this agreement.
- This is program housing: rooms and beds are assigned by the house and may change with notice.
- Guests, overnight passes, and quiet hours follow the Resident Handbook.

## 3. The three-phase program

Your residency moves through three phases. Advancement is a decision made **with** you by
staff — it is based on your stability and readiness, never an automatic timer.

| Phase | Focus | Curfew |
|---|---|---|
| 1 — Foundation | Stabilize, orient, connect, build your plan | 9:00 PM |
| 2 — Growth | Consistency, responsibility, recovery capital | 10:00 PM Sun–Thu / 11:00 PM Fri–Sat |
| 3 — Leadership & Transition | Independence, mentorship, transition | 11:00 PM Sun–Thu / Midnight Fri–Sat |

Curfew never extends past midnight in any phase.

## 4. Participation commitments

- **Work, school, training, or volunteering:** once you are stabilized — a judgment made with
  staff, not a clock — the target is **30 hours per week** of employment, education,
  training, or volunteering combined.
- **Recovery support:** qualifying recovery-support activities each week — **4 per week in
  Phase 1, 3 per week in Phase 2, 2 per week in Phase 3.** Any approved pathway counts:
  mutual-aid meetings of any tradition, SMART Recovery, faith-based recovery, cultural
  practices, peer support, and recovery coaching sessions all count. **No specific pathway
  is ever required.** A sponsor or mentor relationship is strongly encouraged and never
  mandatory.
- **House life:** house meetings, assigned chores, and the community expectations in the
  Resident Handbook.

## 5. Financial terms

Fees are program fees, not rent. They are set and managed by the residence operator (resident
program fees are an operator financial function, not a Grace For Addictions function), and they
are disclosed here, in writing, before any funds are accepted.

**Program fees:**

| Fee | Amount |
|---|---|
| Shared room | **$175 per week**, or **$650 per month** when paid in advance |
| Private room | **$200 per week**, or **$750 per month** when paid in advance |
| One-time move-in fee | **$250** (nonrefundable) |
| Live-Out participation | **$25 per week** |

Standard rates apply unless EJWRH has approved an individualized fee arrangement (a reduced
rate, waiver, scholarship, or payment accommodation). Existing prior agreements may be
honored. An individualized reduction never changes the standard published rate for other
residents.

**When payment is due:**

- Weekly payments may be made at any point during the week; a weekly payment still outstanding
  is addressed at the Sunday house meeting.
- Monthly payments are due on or before the 1st of the month.

**Late payments — grace first:**

- During your **first 30 days** of residency, no late charge applies at all.
- After the first 30 days, a delinquent payment may incur **$5 per day, up to a maximum of
  $50 per delinquent payment period**. The charge is **suspended** while you are keeping to
  an approved hardship/payment arrangement, and it may be **waived** based on timely prior
  communication or documented circumstances.
- **A late payment never automatically ends residency.** Persistent nonpayment is addressed
  through the same documented human process as everything else in this agreement.

**If paying gets hard — the hardship path:**

Financial difficulty is met the way everything here is met: with a conversation first.
Tell staff → agree a written payment arrangement together → the late charge is suspended
while you keep to the arrangement → staff follow up with you → and the arrangement is
modified if your circumstances change. Talking to staff *before* a payment is missed is
always enough to start this path.

**Refunds:** fees are generally nonrefundable. Exceptional refunds are considered case by
case; an approved refund is prorated based on unused residency days. The move-in fee is
nonrefundable.

## 6. A substance-free home: screening

You agree to participate in the drug and alcohol screening described in the Screening Policy —
random or otherwise under the approved policy, requested only by the House Manager, the
designated Liaison, or Executive Leadership, using approved methods (urine screen,
breathalyzer, or oral fluid). Two protections are permanent:

- **Medications you are lawfully prescribed — including MOUD (such as buprenorphine,
  methadone, or naltrexone) — are never a violation.** A screening result consistent with
  your prescription is lawful medication, not a program issue.
- **A positive or concerning result never automatically ends your residency.** What happens
  next always begins with a care conversation (see Section 7).

Your authorization for screening is recorded as a consent you can see in your RecoveryOS
account; the Screening Policy explains the process.

## 7. If return to use happens

Return to use is met with care first. The sequence is always: a **care conversation** with
staff → assessment of your immediate safety and circumstances → intensified support or
referral where appropriate → an honest look at community safety and fit → a **documented
human decision**. Possible outcomes include staying with added support, a modified support
plan, temporary transition to a higher level of care, or — as a last resort and never
automatically — discharge. No screening result, by itself, discharges anyone.

## 8. Nondiscrimination

EJWRH and Grace For Addictions do not discriminate on the basis of race, color, religion,
national origin, sex, disability, familial status, or recovery pathway — **including the use
of prescribed medications for opioid or alcohol use disorder.** MOUD is never grounds for
denial, discharge, or different treatment.

## 9. Safety and conduct

You commit to: no alcohol or illicit drugs in the home; no violence or threats; no weapons;
honesty with staff about safety concerns; and respect for housemates, staff, and neighbors.
Serious safety violations can end residency — through the documented human decision process,
with your rights (Section 10) intact.

## 10. Your rights

Your rights are stated in the Resident Rights & Grievance Process document and are not
reduced by this agreement. They include dignity and respect, freedom from discrimination,
your own clinical providers and medication decisions, access to your own records, and a
grievance process without retaliation.

## 11. Moving out

Planned transitions are worked as part of your recovery plan — staff help you plan the next
step, and the exit process in the Resident Handbook applies. If residency ends for cause, it
follows the documented-decision process above. Personal belongings are handled respectfully
per the Handbook.

## 12. Records and privacy

Your participation records live in RecoveryOS. What is collected is the minimum needed to
support you; who can see it is limited by role; information leaves the organization only
with your specific, revocable, written authorization or as required by law.

## 13. Signing, and your electronic-records choices

By signing you confirm you have read this agreement, had your questions answered, received
the referenced documents, and agree to these terms.

**You choose how to sign.** You may sign electronically in the app, or on paper with staff —
**choosing paper never affects your eligibility, your intake progress, or your move-in.**

**Electronic records disclosure.** If you choose to sign electronically, the following
applies:

- **Scope of your electronic consent.** Your consent covers this agreement and the residence
  documents and records connected to your residency in RecoveryOS. It does not cover
  anything else, and it is not a blanket consent to everything electronic.
- **Your right to paper.** You may have any document — including this agreement — on paper
  instead, at any time.
- **Withdrawing electronic consent.** You may withdraw your consent to electronic records at
  any time by telling any staff member or withdrawing it in the app. Withdrawal takes effect
  going forward: records you already signed remain valid, and future documents are then
  handled on paper.
- **Keeping your contact information current.** Tell staff or update your profile in the app
  when your email address or phone number changes, so records reach you.
- **Paper copies.** You may request a paper copy of any document, including your signed
  agreement, at any time — **at no charge**. Staff will print it for you.
- **What you need to use electronic records.** A current web browser on a phone, tablet, or
  computer with internet access; house devices and staff help are available if you don't
  have your own.
- **If the technology materially changes.** If a change to the system would materially
  affect your ability to access your electronic records, you will be notified and asked to
  re-confirm your consent before it applies to you.
- **Keeping your own copy.** You can view your signed agreement in the app whenever you
  want, print it or save it from your device where the device permits, and always ask staff
  for a paper copy.
- **Persistent access.** Your signed documents remain available to you in the app throughout
  your residency, without restriction, expiration, or copy protection.

**Your electronic signature and intent to be bound.** If you choose electronic signing, you
will first affirmatively confirm the electronic-records consent above, then type your full
name and select **"Sign Participant & Residency Agreement."** Selecting that control is your
electronic signature and your statement of intent to be bound by this agreement, recorded
with the exact document version, its content fingerprint, your identity, and the date and
time.

**Legal notices.** Some notices — where applicable law requires it, including any applicable
eviction, termination, default, or right-to-cure notice — must be delivered to you in
nonelectronic form. Electronic delivery alone is never treated as legally sufficient for
such a notice; the required delivery is made and recorded separately.
$ejwrh_body$, '2026-08-31'::timestamptz
from recoveryos.document_templates t
where t.key = 'ejwrh_participant_agreement'
on conflict (template_id, version) do nothing;

insert into recoveryos.document_versions (template_id, version, body_markdown, published_at)
select t.id, '1.0', $ejwrh_body$# EJWRH Resident Handbook

Ernest & Johnnie White Recovery House · 1414 12th Street, Des Moines, Iowa 50314
Office: 515-220-8771 · ejwrh@rcoiowa.org

Welcome home. This handbook explains daily life at EJWRH. It is here to answer questions,
not to trip you up — if something in it is unclear, ask. Acknowledging this handbook means
you received it and know where to look; the only document you sign is the Participant &
Residency Agreement.

## 1. The three phases

Your time here moves through three phases. Moving up is a conversation and a decision made
with staff based on how you are doing — never an automatic day count.

**Phase 1 — Foundation.** Land, stabilize, get connected. You will build your recovery plan,
meet the house, and start work or education planning. Curfew is 9:00 PM.

**Phase 2 — Growth.** Consistency and responsibility. Working toward 30 hours a week of
work, school, training, or volunteering. Curfew is 10:00 PM Sunday–Thursday, 11:00 PM
Friday–Saturday.

**Phase 3 — Leadership & Transition.** Mentor newer residents, lead in the house, and build
your transition plan. Curfew is 11:00 PM Sunday–Thursday, midnight Friday–Saturday.

Curfew never goes past midnight, in any phase.

## 2. Recovery support — your pathway counts

Qualifying recovery-support activities each week: **4 in Phase 1, 3 in Phase 2, 2 in
Phase 3.** What counts is broad on purpose: mutual-aid meetings of any tradition (12-Step,
SMART, Refuge, faith-based, cultural), recovery coaching sessions, structured peer support.
**No specific pathway is required — ever.** A sponsor or mentor is strongly encouraged and
never mandatory. Activities you already do with your coach or navigator count; nobody logs
the same thing twice.

## 3. Curfew, passes, and overnights

- Be home by your phase curfew unless you have an approved pass.
- Passes (including overnight passes) are requested from the house manager in advance —
  approval considers your phase, safety, and plan.
- Work schedules that conflict with curfew are accommodated with staff approval — tell the
  house manager your schedule.

## 4. House life

- **House meeting: Sunday at 6:30 PM.** Attendance is expected — it's where the week gets
  sorted together, including any outstanding weekly payment.
- **Quiet hours: 9:00 PM to 9:00 AM, every day.** Quiet hours are about noise and
  consideration; they are separate from your phase curfew (Section 1).
- **Chores:** everyone carries a share; assignments are posted and rotate.
- **Guests:** common areas only, during posted hours, sober; no overnight guests.
- **Rooms:** keep your space clean; room and bed assignments can change with notice.
- **House communication:** house announcements run through the house GroupMe. Over time
  announcements move into RecoveryOS — and the commitment is that it will never be more work
  than GroupMe. Screening results and personal matters are never posted in GroupMe.
- **Neighbors:** we are guests of this neighborhood — noise, parking, and property lines
  are respected; being a good neighbor is part of recovery leadership.

## 5. Money

Program fees, payment timing, the first-30-days grace, the late-charge rules, and the
hardship path are all in your Participant & Residency Agreement — one place, no surprises.
The rule worth repeating: if paying is going to be hard this week, say so **before** it is
missed. A written arrangement suspends any late charge while you keep to it, and the Sunday
house meeting is where an outstanding weekly payment gets sorted.

## 6. Safety and emergencies

- **Emergency: call 911 first**, then notify staff.
- **Crisis support: call or text 988** (Suicide & Crisis Lifeline), any time.
- **Iowa Warm Line (non-crisis peer support): 844-775-9276.**
- **Naloxone (Narcan): the house supply is kept near the thermostat.** Additional stock may
  exist elsewhere, but near the thermostat is the location to remember.
- Fire evacuation routes and the severe-weather shelter location are posted in the house.
  Staff walk every new resident through them during intake week.
- If you are worried about another resident's immediate safety, tell staff right away —
  that is care, not snitching.

## 7. Alcohol, drugs, and medications

The house is alcohol- and illicit-drug-free. Screening happens per the Screening Policy you
acknowledged. Your prescribed medications — including MOUD — are yours: **you keep them and
take them yourself**, securely in your own possession, per the Medication & MOUD Policy;
just let the House Manager know about new prescriptions or changes. If you return to use,
what happens next starts with a care conversation, not a discharge — the Return-to-Use
Response Policy explains the sequence.

## 8. Your recovery plan

Shortly after admission you and your coach build your Individual Recovery Plan — what
matters to you, your goals, your people, your next steps. It is generated from the real
work you are already doing; reviews update it, and you own it.

## 9. Moving out

Transition is a goal, not a threat. In Phase 3 your transition plan gets concrete: housing,
income, support network, and what stays in place after you move. When you leave — planned or
not — belongings are handled respectfully, and the door to recovery support does not close.

## 10. Problems and complaints

If something is wrong — with the house, with staff, with a decision — the Resident Rights &
Grievance Process document explains exactly how to raise it, and retaliation for raising it
is prohibited. Your first stop can always be any staff member you trust.
$ejwrh_body$, '2026-08-31'::timestamptz
from recoveryos.document_templates t
where t.key = 'ejwrh_resident_handbook'
on conflict (template_id, version) do nothing;

insert into recoveryos.document_versions (template_id, version, body_markdown, published_at)
select t.id, '1.0', $ejwrh_body$# EJWRH Resident Rights & Grievance Process

Ernest & Johnnie White Recovery House · 1414 12th Street, Des Moines, Iowa 50314
Office: 515-220-8771 · ejwrh@rcoiowa.org

These rights are yours from the day you apply. Nothing you sign at EJWRH reduces them.

## Your rights

1. **Dignity and respect.** You are a person in recovery, never a case, a diagnosis, or a
   history. No shame. No stigma. Just grace.
2. **Freedom from discrimination** — including your recovery pathway and your use of
   prescribed medications for opioid or alcohol use disorder (MOUD). Taking your prescribed
   medication is never a violation and never grounds for different treatment.
3. **Your own care.** You choose your clinical providers. Nobody at the residence makes
   medical decisions for you or requires you to change medications.
4. **Safety.** A home free of alcohol, illicit drugs, violence, and harassment.
5. **Your information.** What is collected about you is the minimum needed to support you.
   You can see your own records. Information leaves the organization only with your
   specific, written, revocable authorization — or where the law requires it.
6. **Honest process.** Decisions that affect your residency — including anything following a
   screening result — are made by people, explained to you, and documented. No automated
   decision ends anyone's residency.
7. **Your voice.** You can raise concerns, file grievances, and participate in house
   decisions without fear of retaliation.
8. **Your belongings.** Personal property is respected and handled per the Handbook,
   including when residency ends.

## Your responsibilities

Respect the same rights in others: housemates' dignity, safety, privacy, and property; the
house commitments in your Participant & Residency Agreement; and honesty with the people
walking beside you.

## The grievance process

1. **Say it.** Raise the concern with any staff member you trust — in person, in writing, or
   through the app. If it concerns that person, go to the House Manager or any Grace For
   Addictions staff member instead. Staff may offer to resolve it informally first —
   **informal resolution is an offer, never a requirement**; you can go straight to a formal
   grievance.
2. **It gets acknowledged — within 1 business day.** A formal grievance is written down and
   acknowledged to you within one business day of receipt. You get a copy on request.
3. **It gets answered — within 5 business days.** You receive a written initial response
   within five business days. If the matter needs more review than that allows, you are told
   it remains open and given an expected completion date — it never just goes quiet.
4. **You can appeal — within 5 business days of the response.** Your appeal goes to the
   Operator or an authorized executive designee **who was not responsible for the original
   decision, wherever reasonably possible** — a role, not a favor. The final appeal
   determination comes within **10 business days**.
5. **No retaliation — ever.** Filing a grievance can never be used against you in phase
   decisions, passes, screening responses, or residency decisions.

**Outside voices are always yours.** External advocacy and complaint options remain
available to you at any time — before, during, or after this process — including the Iowa
affiliate (MCRSP) for recovery-residence standards concerns.
$ejwrh_body$, '2026-08-31'::timestamptz
from recoveryos.document_templates t
where t.key = 'ejwrh_resident_rights_grievance'
on conflict (template_id, version) do nothing;

insert into recoveryos.document_versions (template_id, version, body_markdown, published_at)
select t.id, '1.0', $ejwrh_body$# EJWRH Screening Policy

Ernest & Johnnie White Recovery House · 1414 12th Street, Des Moines, Iowa 50314

Screening exists to keep the home safe for everyone's recovery — it is a safety practice,
not a trap. This policy explains how it works; your separate screening consent (which you
can see in your account) is what authorizes it.

## How screening works

- Screening may be **random**, and may otherwise be conducted under this approved policy
  (including for a safety concern staff can articulate).
- A test may be requested and administered only by the **House Manager**, the **designated
  Liaison**, or **Executive Leadership** — no one else.
- Approved methods: **urine screen (UA)**, **breathalyzer**, and **oral-fluid (saliva)**
  testing. Screening is conducted respectfully and privately.

## Refusing or missing a test

Directly refusing a properly communicated test, or failing to appear for one without a
reasonable explanation, may be treated as a refusal — which starts a conversation and is
documented, never an automatic consequence. **Legitimate temporary unavailability — being at
work, at an appointment, or otherwise genuinely unreachable — is not a refusal** and is never
automatically labeled one.

## If you dispute a result

A nonnegative result you contest can be checked, under this policy and at resident expense:

- **immediate repeat testing** where appropriate; and/or
- **confirmatory laboratory testing.**

While verification is pending, the result is recorded as **contested / unconfirmed** — not
as a positive — and no residency decision is made from it.

## What results mean — three permanent protections

1. **Prescribed medication is never a violation.** A result consistent with a medication you
   are lawfully prescribed — including MOUD such as buprenorphine, methadone, or naltrexone —
   is lawful medication. It is not a positive result for program purposes.
2. **No result automatically ends residency.** A positive or concerning result always leads
   first to a care conversation: how are you, what happened, what do you need. Then an
   assessment of immediate safety, intensified support or clinical referral where it fits,
   an honest look at community safety and continued fit, and a **documented human decision**
   — facilitated by the Operator, the designated Liaison, and/or authorized Executive
   Leadership. Outcomes range from staying with more support, to a modified plan or a
   temporary higher level of care, to — as a last resort — discharge.
3. **Results are private.** Screening results are visible only to the roles with an
   operational need. They are **never posted in GroupMe**, never put in general coaching
   notes, and leave the organization only under applicable authority or your specific
   written consent — with an audit record either way.

## Your consent

Your authorization to participate in screening is recorded as a consent grant at intake.
You may revoke it at any time by telling staff — revocation is honored going forward and
starts a conversation about whether the program can still work for you; it is never punished
and never triggers an automatic discharge.
$ejwrh_body$, '2026-08-31'::timestamptz
from recoveryos.document_templates t
where t.key = 'ejwrh_screening_policy'
on conflict (template_id, version) do nothing;

insert into recoveryos.document_versions (template_id, version, body_markdown, published_at)
select t.id, '1.0', $ejwrh_body$# EJWRH Medication & MOUD Policy

Ernest & Johnnie White Recovery House · 1414 12th Street, Des Moines, Iowa 50314

## The commitment first

**Medication for opioid or alcohol use disorder (MOUD/MAT) — buprenorphine, methadone,
naltrexone, and others prescribed to you — is recovery, not a compromise of it.** Taking
your prescribed medication is never a violation, never grounds for denial or discharge, and
never treated differently from any other prescription. Nobody at EJWRH will pressure you to
change, taper, or stop a medication — those decisions belong to you and your prescriber.

## Your medications stay yours

- **You keep your own medications and take them yourself.** EJWRH and Grace For Addictions
  do not routinely administer, dispense, or dose anyone's medication.
- There is **no house lockbox requirement and no house medication safe requirement.** Your
  medications remain securely in your own possession — stored so housemates can't get to
  them, which protects you and them.
- Where a specific situation genuinely warrants it, an **individual secure-storage
  arrangement can be set up case by case** with the House Manager — an exception built with
  you, never a blanket rule.

## What the house needs to know

- At intake, staff review your current medications with you and record the minimum: the
  medication name, how it's stored, and whether a prescriber is on file. **No dosages, no
  diagnoses, and no medical history are collected.** If you take no medications, staff
  simply record that the review happened.
- **New prescriptions or material changes: tell the House Manager** so the residence's
  safety and storage documentation stays current — that's the whole ask.
- For controlled medications, all that's needed is **reasonable evidence they are lawfully
  prescribed** — current labeled packaging or a medication list is preferred; targeted
  verification only where genuinely needed. Nobody asks for your clinical records.

## If something goes missing

Report lost or missing medication to staff immediately. Missing controlled medication is a
safety issue for the whole house and is documented and handled without assuming fault.
$ejwrh_body$, '2026-08-31'::timestamptz
from recoveryos.document_templates t
where t.key = 'ejwrh_medication_moud_policy'
on conflict (template_id, version) do nothing;

insert into recoveryos.document_versions (template_id, version, body_markdown, published_at)
select t.id, '1.0', $ejwrh_body$# EJWRH Return-to-Use Response Policy

Ernest & Johnnie White Recovery House · 1414 12th Street, Des Moines, Iowa 50314

Return to use is part of many recovery stories. At EJWRH it is met with care first —
and never with an automatic consequence.

## The sequence — every time

1. **Care conversation.** Before anything else, a staff member sits down with you: how are
   you, what happened, are you safe right now.
2. **Safety assessment.** Immediate risks first — yours and the house's. If medical care is
   needed, it comes before everything else (911 for emergencies; 988 for crisis support).
3. **Support response.** Where it fits: intensified recovery support, more frequent coaching
   contact, a clinical or higher-level-of-care referral — built with you, not done to you.
4. **Community fit.** An honest look at the safety of the house community and whether the
   program can keep supporting you well right now.
5. **Documented human decision.** A person decides, explains the decision to you, and
   documents it — the care-response decision is facilitated by the Operator, the designated
   Liaison, and/or authorized Executive Leadership. Possible outcomes: remain with added
   support, a modified support plan, temporary transition to a higher level of care, or — as
   a last resort — discharge.

**No screening result ends a residency by itself.** There is no automatic discharge in this
house, and the software the house runs on is built so none can exist.

## What stays true throughout

- Your prescribed medications, including MOUD, are never part of the problem — a
  prescription-consistent result is lawful medication, not return to use.
- A result you contest is recorded as contested/unconfirmed while it is verified (see the
  Screening Policy) — this sequence runs on confirmed reality, not on a disputed strip.
- Honesty helps you. Telling staff before a screen is always better received than a
  surprise result — the sequence above starts at step 1 either way.
- If residency does end, it ends with a plan: belongings handled respectfully, referrals
  offered, and the door to Grace For Addictions recovery support stays open.
- Iowa's Good Samaritan protections may apply when someone in good faith seeks emergency
  help for an overdose — **calling 911 for yourself or a housemate is always the right
  call, and this house will never punish it.**
$ejwrh_body$, '2026-08-31'::timestamptz
from recoveryos.document_templates t
where t.key = 'ejwrh_return_to_use_response_policy'
on conflict (template_id, version) do nothing;

-- 3) Hash verification: ABORT unless every seeded version hashes to the pinned
--    expectation (content_hash computed by the 0139 trigger on insert).
do $$
declare v_bad text;
begin
  select string_agg(t.key || '=' || coalesce(dv.content_hash, 'NULL'), ', ') into v_bad
  from recoveryos.document_templates t
  join recoveryos.document_versions dv on dv.template_id = t.id and dv.version = '1.0'
  where t.key like 'ejwrh_%'
    and (t.key, dv.content_hash) not in (
      ('ejwrh_participant_agreement', '1df7e655328419a0a58a6068055f5739876bab4bd604c18dd9dba8ef746719eb'),
      ('ejwrh_resident_handbook', '834773861098c23b4a36785952498d157da39d568cdc015ca41667ff627690ba'),
      ('ejwrh_resident_rights_grievance', '285ce0974c803eb8afb134df20ba21175995c320520c9ccc513822fb44167024'),
      ('ejwrh_screening_policy', 'a835849688a9515e5a0adb4d7d43941717fdaefb415748e2b8f98106612cd6c7'),
      ('ejwrh_medication_moud_policy', '6412db49cfe42cbfdfb81beb2d70e2310c42837407820ff90ad1f4dfdd7d605f'),
      ('ejwrh_return_to_use_response_policy', 'c4cbe7669007474cb9e6a4c5178ab4968277ec4cfa28efbb0f050fa07ad86a97'));
  if v_bad is not null then
    raise exception 'EJWRH ACTIVATION ABORT: seeded text does not match the ratified hashes: %', v_bad;
  end if;
  if (select count(*) from recoveryos.document_templates t
      join recoveryos.document_versions dv on dv.template_id = t.id
        and dv.version = '1.0' and dv.published_at is not null
      where t.key like 'ejwrh_%') <> 6 then
    raise exception 'EJWRH ACTIVATION ABORT: expected exactly 6 published v1.0 editions';
  end if;
end $$;

notify pgrst, 'reload schema';
