
const images={"original_lobby": "assets/original_lobby.png"};
document.querySelectorAll('[data-img]').forEach(el=>el.src=images[el.dataset.img]);
const services={
coaching:{title:'A person in your corner.',tag:'Recovery coaching & peer support',intro:'Explore goals, strengths, and what moving forward means to you.',items:[['Recovery coaching','A collaborative conversation around the life you want to build.'],['Peer support','Connection grounded in lived experience and mutual respect.'],['A first conversation','Ask questions before deciding whether ongoing support is right for you.']],boundary:'Learn and contact the front desk as a guest. Ongoing scheduling and private messages would use an account and the appropriate permissions.'},
navigation:{title:'Practical support. A place to start.',tag:'Resource navigation',intro:'Start with the need you want help with—not a long intake questionnaire.',items:[['Housing and stability','Explore housing information and ask about eligibility and availability.'],['Work, transport and essentials','Find help with employment, rides, food, benefits, or identification.'],['Warm connections','A future navigator handoff should show who is following up and what happens next.']],boundary:'A live directory must show the resource owner, service area, eligibility, contact information, and last verification date. This demo contains no live resource inventory.'},
housing:{title:'Explore places. Understand the next step.',tag:'Recovery housing',intro:'Learn about Grace House, EJWRH, and partner options before choosing where to apply.',items:[['Grace House','Women’s recovery residence information and its own application pathway.'],['EJWRH','Separate residence, admission authority, and application pathway; GFA provides wraparound support.'],['Before applying','Show verified fees, eligibility, house expectations, accessibility, and a clear intake contact.']],boundary:'No bed availability or admission is promised. General information stays public. An application may collect necessary information without forcing account creation; status tracking can be offered afterward.'},
learn:{title:'A little learning. A little growth.',tag:'Learn / optional daily practice',intro:'Choose what helps you today. Your interests can change.',items:[['Recovery and practical life skills','Short lessons, reflection prompts, and skills you can try.'],['A daily moment','Optional gratitude, mindfulness, creativity, or a quiet pause.'],['Faith and spiritual exploration','Explicitly opt into Scripture, prayer, or other faith-based material. Never required for support.']],boundary:'Read public samples without an account. An account can save your chosen tracks and progress. Notifications and faith content should each have their own optional controls.'},
ally:{title:'Connection reaches beyond one person.',tag:'Families / allies / community',intro:'Find a useful way to show up for someone or participate in community.',items:[['Support someone you care about','Explore respectful, person-first ways to offer connection.'],['Volunteer or become an ally','Understand the role, boundaries, training, and next steps before applying.'],['Partner with GFA','Ask about referral coordination and community support.']],boundary:'Public information and an initial inquiry stay open. Volunteer/staff authority requires separate onboarding and approval; a public account does not grant access to participant information.'},
reentry:{title:'Connection across the transition.',tag:'ANCHOR / Reentry information',intro:'Explore support before release, through transition, and into community.',items:[['Connect before release','Understand referral options and plan for practical needs.'],['Bridge and stabilize','Coordinate a first destination, transportation, community connections, and appointments.'],['Build long-term recovery capital','Explore work, housing retention, belonging, and personal milestones.']],boundary:'This is proposed public orientation, not enrollment or a placement guarantee. Referral coordination and information sharing require the appropriate process and permission.'},
grace:{title:'Help finding a starting point.',tag:'Grace AI / proposed opt-in',intro:'A clearly identified AI navigation option—alongside easy access to a person.',items:[['Know what Grace is','An AI support navigator, not a human peer, therapist, sponsor, or crisis line.'],['See the basis for a suggestion','Show verified resource sources, dates, eligibility, and uncertainty.'],['Stay in control','Choose whether to continue, share information, or connect with a person.']],boundary:'No AI service is connected in this prototype. Before launch, approve the knowledge sources, consent, privacy, crisis routing, and human handoff. Do not infer emotions or automate participant decisions.'},
private:{title:'Keep your next chapter connected.',tag:'Private continuity',intro:'An account can help you return to your plan and your support connections.',items:[['Saved next steps','Keep resources and choices across visits.'],['Private conversations','Use approved messaging and consent-based coordination.'],['Personal milestones','Record your own progress and choose how it is shared.']],boundary:'This requires a real authenticated account in production. The prototype offers only a synthetic member preview.'}
};
const tiles=[['circles','◎','Find a recovery circle','Meeting information & what to expect','guest','meetings groups community'],['coaching','↔','Connect with a person','Coaching, peers & the front desk','guest','coach support talk'],['navigation','⌁','Find practical resources','Housing, work, food & transportation','guest','jobs benefits rides'],['housing','⌂','Explore recovery housing','Understand options before applying','guest','residence grace house ejwrh'],['learn','✦','Learn something useful','Daily practice & optional tracks','guest','reading faith prayer meditation'],['reentry','↗','Explore ANCHOR','Connection through reentry','guest','justice release prison'],['ally','○','Support someone or volunteer','Family, allies & partnerships','guest','help volunteer family'],['grace','◇','Explore Grace AI','See the proposed navigation option','guest','ai navigator'],['private','▣','Continue my journey','Save, message & follow up','account','account progress private']];
let current='entry',currentService='navigation',plan=[],member=false,recorded=false,toastTimer;
function show(id){if(!document.getElementById(id))return;document.getElementById('toast').hidden=true;clearTimeout(toastTimer);document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==id);current=id;document.querySelectorAll('.nav [data-go]').forEach(b=>{if(b.dataset.go===id)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});if(id==='plan')renderPlan();if(id==='kiosk')renderTiles();window.scrollTo(0,0);const h=document.querySelector('#'+id+' h1');if(h)h.focus({preventScroll:true});}
function notify(message){const el=document.getElementById('toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,4000)}
function addItem(key,label){if(!plan.some(i=>i.key===key))plan.push({key,label});document.getElementById('savedCount').textContent=plan.length+' item'+(plan.length!==1?'s':'')+' in this visit’s plan';notify('Added to this visit’s plan. Nothing was sent.');}
function service(key){currentService=key;const s=services[key];document.getElementById('serviceTitle').textContent=s.title;document.getElementById('serviceTag').textContent=s.tag;document.getElementById('serviceIntro').textContent=s.intro;document.getElementById('serviceCrumb').textContent=s.tag;document.getElementById('serviceBoundary').textContent=s.boundary;const list=document.getElementById('serviceList');list.replaceChildren();s.items.forEach(([a,b])=>{const li=document.createElement('li'),strong=document.createElement('b'),span=document.createElement('span');strong.textContent=a;span.textContent=b;li.append(strong,span);list.append(li)});document.getElementById('serviceMessage').textContent='';show('service')}
function account(reason){const reasons={plan:'Save your next steps so they’re here when you return.',reminders:'Keep selected circles and choose whether to receive reminders.',continue:'Continue with private, ongoing support when you choose.'};document.getElementById('accountReason').textContent=reasons[reason]||'An account gives you a private place to continue.';show('account')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-go],[data-service],[data-account-reason]');if(!b)return;if(b.dataset.go)show(b.dataset.go);if(b.dataset.service)service(b.dataset.service);if(b.dataset.accountReason)account(b.dataset.accountReason)});
function renderTiles(){const q=document.getElementById('kioskSearch').value.toLowerCase().trim(),a=document.getElementById('accessFilter').value;const box=document.getElementById('tiles');box.replaceChildren();tiles.filter(t=>(a==='all'||t[4]===a)&&t.join(' ').toLowerCase().includes(q)).forEach(t=>{const b=document.createElement('button');b.className='tile';const icon=document.createElement('span');icon.className='tile-icon';icon.setAttribute('aria-hidden','true');icon.textContent=t[1];const strong=document.createElement('strong');strong.textContent=t[2];const small=document.createElement('small');small.textContent=t[3]+' · '+(t[4]==='guest'?'Guest access':'Account for continuity');b.append(icon,strong,small);b.onclick=()=>t[0]==='circles'?show('circles'):t[0]==='private'?account('continue'):service(t[0]);box.append(b)});document.getElementById('noTiles').hidden=box.children.length>0;}
document.getElementById('kioskSearch').addEventListener('input',renderTiles);document.getElementById('accessFilter').addEventListener('change',renderTiles);
document.getElementById('addPlan').onclick=()=>addItem(currentService,services[currentService].tag);document.getElementById('saveCircle').onclick=()=>addItem('circles','Recovery circle information');
function renderPlan(){const el=document.getElementById('planItems');el.replaceChildren();if(!plan.length){const p=document.createElement('p');p.className='status';p.textContent='Your plan is empty. Browse the kiosk and add a next step that feels useful.';el.append(p);return}plan.forEach(item=>{const div=document.createElement('div');div.className='well';const b=document.createElement('b');b.textContent=item.label;const p=document.createElement('p');p.className='small muted';p.textContent='Next step: learn more or ask the front desk for help. This is a choice saved for this visit, not a submitted request.';const btn=document.createElement('button');btn.className='clear-button';btn.textContent='Remove';btn.onclick=()=>{plan=plan.filter(i=>i.key!==item.key);renderPlan();document.getElementById('savedCount').textContent=plan.length+' items in this visit’s plan'};div.append(b,p,btn);el.append(div)})}
document.getElementById('demoMember').onclick=()=>{member=true;document.getElementById('accountNav').textContent='My space (demo)';document.getElementById('accountNav').dataset.go='member';document.querySelectorAll('.guestLabel').forEach(e=>e.textContent='Member preview');show('member')};
document.getElementById('resetKiosk').onclick=()=>{plan=[];member=false;recorded=false;document.getElementById('savedCount').textContent='0 items in this visit’s plan';document.getElementById('accountNav').textContent='Sign in';document.getElementById('accountNav').dataset.go='account';document.querySelectorAll('.guestLabel').forEach(e=>e.textContent='Exploring as a guest');document.getElementById('kioskSearch').value='';document.getElementById('accessFilter').value='all';document.getElementById('circleForm').reset();document.getElementById('circleSummary').replaceChildren();document.getElementById('demoReceipt').hidden=true;document.getElementById('callbackReceipt').hidden=true;document.getElementById('recordDemo').disabled=false;show('entry');notify('This demo visit has been cleared.');};
function toggleText(){document.body.classList.toggle('large-type');document.getElementById('textSize').setAttribute('aria-pressed',document.body.classList.contains('large-type'))}document.getElementById('textSize').onclick=toggleText;document.getElementById('accessText').onclick=toggleText;document.getElementById('printPlan').onclick=()=>window.print();document.getElementById('callbackDemo').onclick=()=>document.getElementById('callbackReceipt').hidden=false;
document.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-format]').forEach(x=>x.setAttribute('aria-pressed',x===b));document.querySelectorAll('[data-event-format]').forEach(x=>x.hidden=b.dataset.format!=='all'&&x.dataset.eventFormat!==b.dataset.format)});
document.getElementById('circleForm').onsubmit=e=>{e.preventDefault();const get=id=>document.getElementById(id).value;const err=document.getElementById('formError');err.textContent='';if(get('endTime')<=get('startTime')){err.textContent='End time must be later than start time for this same-day demo.';return}if(!Number.isInteger(Number(get('headcount')))){err.textContent='Use a whole number for total people present.';return}const summary=document.getElementById('circleSummary');summary.replaceChildren();[['Program',get('program')],['Venue',get('venue')],['When',get('meetingDate')+' · '+get('startTime')+'–'+get('endTime')+' · America/Chicago'],['Facilitators',get('facilitators')],['Reported total',get('headcount')+' people'],['Counting basis',document.getElementById('countBasis').selectedOptions[0].text],['Topic',get('topic')]].forEach(([label,value])=>{const p=document.createElement('p'),strong=document.createElement('b');strong.textContent=label+': ';p.append(strong,document.createTextNode(value));summary.append(p)});if(get('countBasis')==='unknown'){const p=document.createElement('p');p.className='status attention';p.textContent='Needs verification: whether the total includes facilitators. No participant-only count is inferred.';summary.append(p)}document.getElementById('recordDemo').disabled=recorded;show('staffReview')};document.getElementById('recordDemo').onclick=()=>{recorded=true;document.getElementById('demoReceipt').hidden=false;document.getElementById('recordDemo').disabled=true;notify('Demo recorded once. No live record was created.')};
Object.entries(images).forEach(([key,src])=>{const fig=document.createElement('figure'),im=document.createElement('img'),cap=document.createElement('figcaption');im.src=src;im.alt='Original RecoveryOS lobby concept '+key;im.loading='lazy';cap.textContent='Original lobby concept · AI-generated for design review';fig.append(im,cap);document.getElementById('moodboard').append(fig)});renderTiles();
