-- 0201_seed_slogans.sql
-- Recovery slogans exported from dev public.recovery_slogans (59 rows) into recoveryos.slogans.
-- Mapping: slogan_text, slogan_short, author_credit, category, tags, seven factor columns,
-- composite_score, applicable_enneagram_types (int[] cast to text[]), applicable_true_colors,
-- applicable_stages, is_grace_centered = coalesce(is_grace_centered,false), is_active = coalesce(is_active,true).
-- Idempotent: natural key slogan_text (unique constraint slogans_slogan_text_key).

insert into recoveryos.slogans (
  slogan_text, slogan_short, author_credit, category, tags,
  hope_factor, action_factor, community_factor, resilience_factor, identity_factor, grace_factor, neuroplasticity_factor,
  composite_score, applicable_enneagram_types, applicable_true_colors, applicable_stages,
  is_grace_centered, is_active)
values
  ('A return to use is not the end of your story — it is a chapter.', 'A chapter, not the end', 'Recovery Community', 'Resilience', '{return-to-use,grace,resilience}'::text[], '9', '7', '6', '10', '8', '10', '8', '8.3', '{4,9,2}'::text[], '{Blue,Green}'::text[], '{return-to-use}'::text[], 't', 't'),
  ('Between stimulus and response, there is a space. That space is recovery.', 'Space is recovery', 'Recovery Community', 'Mindfulness', '{mindfulness,neuroscience,choice}'::text[], '9', '8', '5', '9', '9', '8', '10', '8.3', '{5,4,9}'::text[], '{Green,Blue}'::text[], '{middle,long-term}'::text[], 't', 't'),
  ('Community prevents crisis.', 'Community prevents crisis', 'Recovery Community', 'Community', '{crisis-prevention,connection,community}'::text[], '9', '7', '10', '9', '7', '8', '8', '8.3', '{6,2,9}'::text[], '{Blue,Gold}'::text[], '{all}'::text[], 't', 't'),
  ('Connection is the opposite of addiction.', 'Connection heals', 'Recovery Community', 'Community', '{connection,community,neuroscience}'::text[], '9', '7', '10', '8', '7', '8', '9', '8.3', '{2,6,9}'::text[], '{Blue,Green}'::text[], '{early,middle}'::text[], 't', 't'),
  ('Do the next right thing.', 'Next right thing', 'Recovery Community', 'Action', '{action,daily,foundation}'::text[], '8', '10', '5', '8', '8', '8', '8', '7.9', '{1,6,2}'::text[], '{Gold,Orange}'::text[], '{early,crisis}'::text[], 't', 't'),
  ('Every moment is a chance to begin again.', 'Begin again', 'Recovery Community', 'Grace', '{grace,neuroplasticity,hope}'::text[], '10', '7', '5', '8', '8', '10', '9', '8.1', '{1,4,7,9}'::text[], '{Blue,Green}'::text[], '{early,return-to-use}'::text[], 't', 't'),
  ('Every sober choice rewires your brain toward freedom.', 'Rewires toward freedom', 'Recovery Community', 'Neuroplasticity', '{neuroscience,neuroplasticity,science,hope}'::text[], '9', '9', '5', '8', '8', '8', '10', '8.1', '{5,1,3}'::text[], '{Green,Orange}'::text[], '{early,middle}'::text[], 't', 't'),
  ('Fall seven times. Stand up eight.', 'Stand up eight', 'Recovery Community', 'Resilience', '{resilience,perseverance,classic}'::text[], '9', '9', '5', '10', '8', '7', '8', '8.0', '{8,3,1}'::text[], '{Orange,Gold}'::text[], '{return-to-use,middle}'::text[], 't', 't'),
  ('God does not waste pain.', 'God does not waste pain', 'Recovery Community', 'Spiritual', '{spiritual,grace,faith,purpose}'::text[], '10', '6', '5', '9', '8', '10', '8', '8.0', '{2,4,9}'::text[], '{Blue,Green}'::text[], '{all}'::text[], 't', 't'),
  ('Grace for addictions means no one walks alone.', 'No one walks alone', 'Recovery Community', 'Grace', '{grace,gfa,mission,community}'::text[], '10', '7', '10', '9', '8', '10', '8', '8.9', '{2,6,9}'::text[], '{Blue,Green}'::text[], '{all}'::text[], 't', 't'),
  ('Grace is not earned. It is given.', 'Grace is given', 'Recovery Community', 'Grace', '{grace,spiritual,faith}'::text[], '10', '5', '6', '8', '8', '10', '7', '7.7', '{2,4,9}'::text[], '{Blue,Green}'::text[], '{all}'::text[], 't', 't'),
  ('Gratitude is a recovery practice, not just a feeling.', 'Gratitude is practice', 'Recovery Community', 'Gratitude', '{gratitude,practice,daily}'::text[], '9', '7', '6', '8', '7', '9', '8', '7.7', '{2,9,4}'::text[], '{Blue,Green}'::text[], '{all}'::text[], 't', 't'),
  ('Healing is not linear. And that is okay.', 'Healing is not linear', 'Recovery Community', 'Grace', '{grace,healing,self-compassion}'::text[], '9', '6', '5', '9', '8', '10', '9', '8.0', '{4,2,9}'::text[], '{Blue,Green}'::text[], '{return-to-use,early}'::text[], 't', 't'),
  ('I am a person in recovery. That is a source of strength.', 'Strength in identity', 'Recovery Community', 'Identity', '{identity,pride,strength}'::text[], '9', '7', '7', '9', '10', '9', '8', '8.4', '{3,8,1}'::text[], '{Orange,Gold}'::text[], '{middle,long-term}'::text[], 't', 't'),
  ('I am living proof that recovery works.', 'Living proof', 'Recovery Community', 'Identity', '{identity,advocacy,hope}'::text[], '10', '7', '8', '9', '10', '9', '8', '8.7', '{3,8,2}'::text[], '{Orange,Blue}'::text[], '{long-term}'::text[], 't', 't'),
  ('I am not what happened to me. I am what I choose to become.', 'Choose to become', 'Recovery Community', 'Identity', '{identity,agency,choice}'::text[], '9', '9', '5', '9', '10', '9', '9', '8.6', '{4,8,3}'::text[], '{Orange,Green}'::text[], '{early,middle}'::text[], 't', 't'),
  ('I got well so others would know it is possible.', 'So others know', 'Recovery Community', 'Advocacy', '{advocacy,hope,peer}'::text[], '10', '8', '9', '8', '9', '9', '7', '8.6', '{2,8,3}'::text[], '{Blue,Orange}'::text[], '{long-term}'::text[], 't', 't'),
  ('I have survived every hard day so far. Today is no different.', 'Survived every hard day', 'Recovery Community', 'Resilience', '{resilience,daily,self-efficacy}'::text[], '9', '8', '5', '10', '9', '8', '8', '8.1', '{8,6,1}'::text[], '{Gold,Orange}'::text[], '{crisis,early}'::text[], 't', 't'),
  ('Isolation is the enemy of recovery. Connection is its cure.', 'Connection cures', 'Recovery Community', 'Community', '{isolation,connection,community}'::text[], '9', '7', '10', '9', '7', '9', '8', '8.4', '{4,5,9}'::text[], '{Blue,Green}'::text[], '{early,middle,crisis}'::text[], 't', 't'),
  ('Long-term recovery is a long-term investment worth making.', 'Long-term investment', 'Recovery Community', 'Advocacy', '{long-term,policy,sustainability}'::text[], '9', '8', '7', '9', '9', '8', '8', '8.3', '{3,1,8}'::text[], '{Gold,Orange}'::text[], '{long-term}'::text[], 't', 't'),
  ('My past prepared me. It does not define me.', 'Prepared, not defined', 'Recovery Community', 'Identity', '{identity,narrative,grace}'::text[], '9', '7', '5', '9', '10', '10', '8', '8.3', '{4,6,9}'::text[], '{Blue,Green}'::text[], '{middle,long-term}'::text[], 't', 't'),
  ('My recovery is a gift to everyone who loves me.', 'Gift to those who love me', 'Recovery Community', 'Community', '{family,community,gratitude}'::text[], '10', '7', '9', '8', '9', '9', '8', '8.6', '{2,4,9}'::text[], '{Blue,Green}'::text[], '{all}'::text[], 't', 't'),
  ('New neural pathways are being built every time you choose recovery.', 'New pathways', 'Recovery Community', 'Neuroplasticity', '{neuroscience,neuroplasticity,choice}'::text[], '9', '9', '5', '8', '8', '8', '10', '8.1', '{5,3,1}'::text[], '{Green,Orange}'::text[], '{early,middle}'::text[], 't', 't'),
  ('Nothing about us without us.', 'Nothing without us', 'Recovery Community', 'Advocacy', '{advocacy,peer,empowerment}'::text[], '8', '9', '9', '8', '9', '8', '7', '8.3', '{8,1,3}'::text[], '{Orange,Gold}'::text[], '{all}'::text[], 't', 't'),
  ('One day at a time.', 'One day at a time', 'Recovery Community', 'Hope', '{daily,foundation,classic}'::text[], '10', '6', '6', '8', '7', '8', '7', '7.4', '{1,2,6,9}'::text[], '{Blue,Gold}'::text[], '{early,middle,long-term}'::text[], 't', 't'),
  ('Pain is not punishment. It is information.', 'Pain is information', 'Recovery Community', 'Resilience', '{trauma,resilience,neuroscience}'::text[], '8', '7', '5', '9', '8', '9', '9', '7.9', '{4,1,5}'::text[], '{Green,Blue}'::text[], '{early,middle}'::text[], 't', 't'),
  ('Peer support works because lived experience speaks.', 'Lived experience speaks', 'Recovery Community', 'Peer', '{peer,lived-experience,advocacy}'::text[], '9', '8', '9', '8', '9', '8', '8', '8.4', '{2,8,3}'::text[], '{Blue,Orange}'::text[], '{all}'::text[], 't', 't'),
  ('Progress, not perfection.', 'Progress not perfection', 'Recovery Community', 'Action', '{action,grace,classic}'::text[], '8', '9', '5', '8', '8', '10', '8', '8.0', '{1,3,6}'::text[], '{Gold,Orange}'::text[], '{all}'::text[], 't', 't'),
  ('Purpose is the most powerful medicine.', 'Purpose is medicine', 'Recovery Community', 'Purpose', '{purpose,identity,spiritual}'::text[], '10', '7', '6', '9', '9', '9', '9', '8.4', '{1,2,4}'::text[], '{Blue,Green}'::text[], '{middle,long-term}'::text[], 't', 't'),
  ('Radical grace means no one is too far gone.', 'No one too far gone', 'Recovery Community', 'Grace', '{grace,hope,radical}'::text[], '10', '6', '7', '9', '8', '10', '8', '8.3', '{2,4,6,9}'::text[], '{Blue,Green}'::text[], '{all}'::text[], 't', 't'),
  ('Recovery gave me back myself.', 'Recovery gave me back myself', 'Recovery Community', 'Identity', '{identity,recovery,gratitude}'::text[], '10', '7', '6', '8', '10', '9', '8', '8.3', '{4,2,9}'::text[], '{Blue,Green}'::text[], '{middle,long-term}'::text[], 't', 't'),
  ('Recovery is a team sport.', 'Team sport', 'Recovery Community', 'Community', '{community,peer,connection}'::text[], '8', '7', '10', '8', '7', '8', '7', '7.9', '{2,7,3}'::text[], '{Orange,Blue}'::text[], '{early,middle}'::text[], 't', 't'),
  ('Recovery is freedom. And freedom is worth fighting for.', 'Freedom worth fighting for', 'Recovery Community', 'Advocacy', '{freedom,advocacy,long-term}'::text[], '10', '9', '7', '9', '9', '8', '8', '8.6', '{8,1,3}'::text[], '{Orange,Gold}'::text[], '{all}'::text[], 't', 't'),
  ('Recovery is not a destination. It is a direction.', 'A direction', 'Recovery Community', 'Action', '{action,identity,long-term}'::text[], '9', '8', '6', '8', '9', '8', '8', '8.0', '{3,1,7}'::text[], '{Orange,Gold}'::text[], '{all}'::text[], 't', 't'),
  ('Recovery is not just personal. It is political.', 'Recovery is political', 'Recovery Community', 'Advocacy', '{advocacy,systems,policy}'::text[], '8', '9', '8', '8', '9', '7', '7', '8.0', '{8,1,6}'::text[], '{Orange,Gold}'::text[], '{long-term}'::text[], 't', 't'),
  ('Recovery is possible for anyone who is willing to do the work.', 'Recovery is possible', 'Recovery Community', 'Hope', '{possibility,motivation,early-recovery}'::text[], '10', '8', '5', '7', '8', '7', '8', '7.6', '{3,8,1}'::text[], '{Orange,Gold}'::text[], '{early,contemplation}'::text[], 't', 't'),
  ('Recovery is showing up — even imperfectly.', 'Showing up', 'Recovery Community', 'Action', '{action,grace,imperfection}'::text[], '8', '9', '5', '8', '8', '10', '7', '7.9', '{1,6,2}'::text[], '{Gold,Blue}'::text[], '{all}'::text[], 't', 't'),
  ('Redemption is not a reward for perfection. It is a gift for the willing.', 'Gift for the willing', 'Recovery Community', 'Grace', '{grace,redemption,spiritual}'::text[], '10', '7', '6', '9', '8', '10', '8', '8.3', '{2,4,9}'::text[], '{Blue,Green}'::text[], '{early,return-to-use}'::text[], 't', 't'),
  ('Small steps are still steps.', 'Small steps count', 'Recovery Community', 'Action', '{action,progress,early-recovery}'::text[], '8', '9', '5', '8', '7', '8', '8', '7.6', '{6,9,2}'::text[], '{Gold,Blue}'::text[], '{early,contemplation}'::text[], 't', 't'),
  ('Storms make trees take deeper roots.', 'Deeper roots', 'Recovery Community', 'Resilience', '{resilience,growth,nature}'::text[], '9', '6', '5', '10', '8', '8', '8', '7.7', '{6,9,1}'::text[], '{Gold,Green}'::text[], '{middle,long-term}'::text[], 't', 't'),
  ('Strength is not the absence of struggle. It is continuing anyway.', 'Strength is continuing', 'Recovery Community', 'Resilience', '{strength,resilience,perseverance}'::text[], '9', '9', '5', '10', '9', '8', '7', '8.1', '{8,1,6}'::text[], '{Orange,Gold}'::text[], '{middle,long-term}'::text[], 't', 't'),
  ('The brain that was changed by addiction can be changed by recovery.', 'Brain changed by recovery', 'Recovery Community', 'Neuroplasticity', '{neuroscience,hope,science}'::text[], '9', '7', '4', '9', '8', '7', '10', '7.7', '{5,1,3}'::text[], '{Green,Orange}'::text[], '{early,middle}'::text[], 't', 't'),
  ('The cravings get quieter. Science says so. Hold on.', 'Cravings get quieter', 'Recovery Community', 'Neuroplasticity', '{neuroplasticity,craving,science,hope}'::text[], '9', '7', '5', '9', '7', '8', '10', '7.9', '{6,1,5}'::text[], '{Gold,Green}'::text[], '{early,crisis}'::text[], 't', 't'),
  ('The life I have today is the life I once could not imagine.', 'Life I could not imagine', 'Recovery Community', 'Hope', '{hope,gratitude,long-term}'::text[], '10', '6', '6', '9', '9', '9', '8', '8.1', '{4,2,9}'::text[], '{Blue,Green}'::text[], '{long-term}'::text[], 't', 't'),
  ('The miracle is in the ordinary.', 'Miracle in ordinary', 'Recovery Community', 'Gratitude', '{gratitude,mindfulness,daily}'::text[], '9', '6', '6', '7', '7', '9', '8', '7.4', '{4,9,2}'::text[], '{Blue,Green}'::text[], '{middle,long-term}'::text[], 't', 't'),
  ('The wound is where the light enters.', 'Where light enters', 'Recovery Community', 'Grace', '{grace,trauma,spiritual}'::text[], '10', '5', '5', '9', '8', '10', '8', '7.9', '{4,2,9}'::text[], '{Blue,Green}'::text[], '{early,middle}'::text[], 't', 't'),
  ('There is no shame in asking for help. There is only courage.', 'Courage to ask', 'Recovery Community', 'Grace', '{shame-reduction,grace,courage}'::text[], '8', '7', '8', '8', '7', '10', '7', '7.9', '{2,6,1}'::text[], '{Blue,Gold}'::text[], '{early,contemplation}'::text[], 't', 't'),
  ('Today I have what I need.', 'Today I have enough', 'Recovery Community', 'Mindfulness', '{mindfulness,gratitude,daily}'::text[], '9', '6', '5', '8', '7', '9', '7', '7.3', '{9,4,2}'::text[], '{Blue,Green}'::text[], '{all}'::text[], 't', 't'),
  ('We cannot think our way into right living. We have to live our way into right thinking.', 'Live into right thinking', 'Recovery Community', 'Action', '{action,community,neuroscience}'::text[], '8', '9', '7', '8', '7', '7', '9', '7.9', '{5,1,6}'::text[], '{Gold,Green}'::text[], '{middle,long-term}'::text[], 't', 't'),
  ('We do not recover alone. And we do not give back alone either.', 'Give back together', 'Recovery Community', 'Community', '{community,service,giving-back}'::text[], '9', '8', '10', '8', '8', '9', '7', '8.4', '{2,6,9}'::text[], '{Blue,Gold}'::text[], '{long-term}'::text[], 't', 't'),
  ('What we cannot do alone, we can do together.', 'Together we can', 'Recovery Community', 'Community', '{community,peer,collective,strength}'::text[], '9', '8', '10', '8', '7', '9', '7', '8.3', '{2,6,9}'::text[], '{Blue,Green}'::text[], '{all}'::text[], 't', 't'),
  ('When one person recovers, the whole community heals.', 'Community heals', 'Recovery Community', 'Community', '{community,systems,ripple-effect}'::text[], '10', '7', '10', '8', '8', '9', '8', '8.6', '{2,9,4}'::text[], '{Blue,Green}'::text[], '{all}'::text[], 't', 't'),
  ('You are not too broken to be whole.', 'Not too broken', 'Recovery Community', 'Grace', '{grace,healing,worth}'::text[], '10', '6', '5', '9', '9', '10', '8', '8.1', '{4,2,9}'::text[], '{Blue,Green}'::text[], '{crisis,early}'::text[], 't', 't'),
  ('You are not your addiction. You are not your past.', 'Not your past', 'Recovery Community', 'Identity', '{identity,shame-reduction,grace}'::text[], '9', '5', '5', '8', '10', '10', '8', '7.9', '{4,2,9}'::text[], '{Blue,Green}'::text[], '{early,middle}'::text[], 't', 't'),
  ('You are worthy of recovery. Full stop.', 'Worthy of recovery', 'Recovery Community', 'Grace', '{grace,worth,shame-reduction}'::text[], '10', '6', '6', '8', '9', '10', '8', '8.1', '{2,4,9}'::text[], '{Blue,Green}'::text[], '{early,crisis}'::text[], 't', 't'),
  ('You do not have to do this alone.', 'Not alone', 'Recovery Community', 'Community', '{community,support,connection}'::text[], '9', '6', '10', '8', '7', '9', '7', '8.0', '{2,6,4,9}'::text[], '{Blue,Green}'::text[], '{early,crisis}'::text[], 't', 't'),
  ('Your best thinking got you here. New thinking will take you further.', 'New thinking', 'Recovery Community', 'Action', '{neuroplasticity,growth,change}'::text[], '8', '9', '5', '8', '8', '7', '10', '7.9', '{5,1,3}'::text[], '{Green,Orange}'::text[], '{early,middle}'::text[], 't', 't'),
  ('Your brain is not broken. It adapted. Now it is adapting again.', 'Adapting again', 'Recovery Community', 'Neuroplasticity', '{neuroscience,hope,reframe}'::text[], '9', '7', '5', '9', '9', '8', '10', '8.1', '{5,1,4}'::text[], '{Green,Blue}'::text[], '{early,middle}'::text[], 't', 't'),
  ('Your story is not over.', 'Story not over', 'Recovery Community', 'Hope', '{hope,identity,narrative}'::text[], '10', '6', '5', '9', '9', '9', '7', '7.9', '{4,9,2}'::text[], '{Blue,Green}'::text[], '{crisis,return-to-use,early}'::text[], 't', 't')
on conflict (slogan_text) do update set
  slogan_short = excluded.slogan_short,
  author_credit = excluded.author_credit,
  category = excluded.category,
  tags = excluded.tags,
  hope_factor = excluded.hope_factor,
  action_factor = excluded.action_factor,
  community_factor = excluded.community_factor,
  resilience_factor = excluded.resilience_factor,
  identity_factor = excluded.identity_factor,
  grace_factor = excluded.grace_factor,
  neuroplasticity_factor = excluded.neuroplasticity_factor,
  composite_score = excluded.composite_score,
  applicable_enneagram_types = excluded.applicable_enneagram_types,
  applicable_true_colors = excluded.applicable_true_colors,
  applicable_stages = excluded.applicable_stages,
  is_grace_centered = excluded.is_grace_centered,
  is_active = excluded.is_active;
