#!/usr/bin/env python3
"""Import the Enneagram personality layer of the slogan engine.

Source: `GFA_Enneagram_Slogan_Map.pdf` — "Complete Mapping: 9 Types × 59
Slogans", the personality layer of the slogan recommendation engine. Maps to
`slogan_personality_maps` with `framework_type_id = enneagram`.

WHAT IS IMPORTED: the structural mapping only — slogan number, Enneagram type,
relevance weight (1–5), and context (core / growth / stress / wing), plus each
type's name, growth direction, and signature slogans. These are numbers and
keywords and extract exactly.

WHAT IS NOT IMPORTED: the `recommendation_note` prose and the Part One type
profiles. The PDF's text runs are concatenated without spaces at line breaks
("the fourth foundation waswritten for you"), and repairing that automatically
would require guessing word boundaries in participant-facing copy. Those notes
need a markdown/source export, like the one that exists for the slogans
themselves. The engine works on structure; the notes drop in later without
rework.

Run: python3 scripts/import-enneagram.py
"""

import json
import re
import zlib
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'docs/source-documents/recovering-the-mind/GFA_Enneagram_Slogan_Map.pdf'
OUT_TS = ROOT / 'packages/recovery-content/src/enneagram.generated.ts'

MAP_RE = re.compile(r'Type (\d)\s*!\s*Weight:\s*(\d)\s*!\s*Context:\s*(\w+)')
TYPE_NAME_RE = re.compile(r'Type (\d)\s*—\s*The ([A-Za-z]+)')
GROWTH_RE = re.compile(r'Growth direction:\s*Toward Type (\d)')
SIGNATURE_RE = re.compile(r'Signature\s*slogans:\s*([\d,\s]+)')

VALID_CONTEXTS = {'core', 'growth', 'stress', 'wing'}


def pdf_text(path: Path) -> str:
    raw = path.read_bytes()
    runs = []
    for m in re.finditer(rb'stream\r?\n(.*?)endstream', raw, re.S):
        try:
            data = zlib.decompress(m.group(1))
        except Exception:
            continue
        text = ''.join(
            p[1:-1].decode('latin-1', 'replace')
            for p in re.findall(rb'\((?:\\.|[^\\()])*\)', data)
        )
        if len(text) > 40:
            runs.append(text.replace('\\(', '(').replace('\\)', ')'))
    joined = '\n'.join(runs)
    # Drop binary font-table noise, keep prose-like lines.
    prose = '\n'.join(
        l for l in joined.split('\n')
        if len(re.findall(r'[A-Za-z ]', l)) / max(len(l), 1) > 0.7
    )
    # The producer wrote MacRoman; it was read as latin-1 above.
    return prose.encode('latin-1', 'replace').decode('mac-roman', 'replace')


def parse(text: str) -> tuple[list[dict], list[dict]]:
    # --- per-slogan type mappings -------------------------------------------
    mappings: list[dict] = []
    seen: set[tuple[int, int]] = set()
    blocks = re.split(r'Slogan (\d+):', text)
    for k in range(1, len(blocks) - 1, 2):
        number = int(blocks[k])
        if not 1 <= number <= 59:
            continue
        for m in MAP_RE.finditer(blocks[k + 1]):
            etype, weight, context = int(m.group(1)), int(m.group(2)), m.group(3)
            if context not in VALID_CONTEXTS or not 1 <= etype <= 9:
                continue
            key = (number, etype)
            if key in seen:
                continue
            seen.add(key)
            mappings.append({
                'sloganNumber': number,
                'type': etype,
                'weight': weight,
                'context': context,
            })

    # --- type profiles (structural fields only) -----------------------------
    names: dict[int, str] = {}
    for m in TYPE_NAME_RE.finditer(text):
        names.setdefault(int(m.group(1)), m.group(2))

    growth = [int(m.group(1)) for m in GROWTH_RE.finditer(text)]
    signatures = [
        [int(n) for n in re.findall(r'\d+', m.group(1))]
        for m in SIGNATURE_RE.finditer(text)
    ]

    types: list[dict] = []
    for i in range(1, 10):
        types.append({
            'type': i,
            'name': names.get(i, ''),
            'growthDirection': growth[i - 1] if i - 1 < len(growth) else 0,
            'signatureSlogans': signatures[i - 1] if i - 1 < len(signatures) else [],
        })

    return mappings, types


def ts(value) -> str:
    return json.dumps(value, ensure_ascii=False)


def emit(mappings: list[dict], types: list[dict]) -> str:
    out = [
        '// GENERATED by scripts/import-enneagram.py — do not edit by hand.',
        '// Source: GFA_Enneagram_Slogan_Map.pdf © 2026 Thomas DeGarmeaux and',
        '// Grace For Addictions. Structural mapping only — the per-type',
        '// recommendation notes need a clean source export (see the script).',
        '',
        "import type { EnneagramMapping, EnneagramType } from './types';",
        '',
        'export const ENNEAGRAM_TYPES: EnneagramType[] = [',
    ]
    for t in types:
        out.append(
            f'  {{ type: {t["type"]}, name: {ts(t["name"])}, '
            f'growthDirection: {t["growthDirection"]}, '
            f'signatureSlogans: {ts(t["signatureSlogans"])} }},'
        )
    out += ['];', '', 'export const ENNEAGRAM_MAPPINGS: EnneagramMapping[] = [']
    for m in sorted(mappings, key=lambda x: (x['sloganNumber'], -x['weight'], x['type'])):
        out.append(
            f'  {{ sloganNumber: {m["sloganNumber"]}, type: {m["type"]}, '
            f'weight: {m["weight"]}, context: {ts(m["context"])} }},'
        )
    out += ['];', '']
    return '\n'.join(out)


def main() -> None:
    mappings, types = parse(pdf_text(SOURCE))

    covered = {m['sloganNumber'] for m in mappings}
    assert covered == set(range(1, 60)), f'slogans without mappings: {sorted(set(range(1,60)) - covered)}'
    assert len(mappings) >= 150, f'suspiciously few mappings: {len(mappings)}'
    for m in mappings:
        assert 1 <= m['weight'] <= 5, f'weight out of range: {m}'
    for t in types:
        assert t['name'], f'type {t["type"]}: missing name'
        assert t['signatureSlogans'], f'type {t["type"]}: missing signature slogans'

    OUT_TS.parent.mkdir(parents=True, exist_ok=True)
    OUT_TS.write_text(emit(mappings, types), encoding='utf-8')

    print(f'Imported {len(mappings)} slogan-type mappings across {len(covered)} slogans')
    print(f'  contexts: {dict(Counter(m["context"] for m in mappings))}')
    names = ', '.join(f'{t["type"]}={t["name"]}' for t in types)
    print(f'  types: {names}')
    print(f'  → {OUT_TS}')


if __name__ == '__main__':
    main()
