#!/usr/bin/env python3
"""Import the 59 slogans from the GFA master source document.

`GFA_59_Slogans_Final.md` describes itself as "the master source document for
GFA's 59 Recovery Slogans... the published book, the peer coach training
curriculum, and the VRCC database seed specification." It supersedes both the
print book and the earlier SQL seed, and it settles the tagging question: its
ICARE phases are explicitly "rebalanced across all five phases" (12/12/12/12/11)
rather than inherited from the book's narrative arc.

Per slogan it carries: ICARE phase (+ id), wellness domain, condensed
commentary (Grace-ready), full commentary, VIA strengths with
rationale, and a practice. The trailing seed-reference table supplies the
stable theme key.

Run: python3 scripts/import-slogans.py
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'docs/source-documents/recovering-the-mind/GFA_59_Slogans_Final.md'
OUT_TS = ROOT / 'packages/recovery-content/src/slogans.generated.ts'

SLOGAN_RE = re.compile(r'^### Slogan (\d+):\s*(.+?)\s*$')
POINT_RE = re.compile(r'^## POINT ([A-Z]+):\s*(.+?)\s*$')
PHASE_RE = re.compile(r'^\*\*ICARE Phase:\*\*\s*(\w+)\s*\((\d)\)')
DOMAIN_RE = re.compile(r'^\*\*Wellness Domain:\*\*\s*(.+?)\s*$')
PRACTICE_RE = re.compile(r'^\*\*Practice:\*\*\s*(.+?)\s*$')
VIA_RE = re.compile(r'^-\s*\*\*(.+?):\*\*\s*(.+?)\s*$')
SEED_ROW_RE = re.compile(r'^\|\s*(\d+)\s*\|\s*(\d)\s*\|\s*(\w+)\s*\|\s*(\w+)\s*\|')

FIELD = '**'


def parse_themes(lines: list[str]) -> dict[int, str]:
    """Theme keys from the trailing `recovery_slogans` seed table."""
    themes: dict[int, str] = {}
    for line in lines:
        m = SEED_ROW_RE.match(line.strip())
        if m:
            themes[int(m.group(1))] = m.group(4)
    return themes


def parse(text: str) -> list[dict]:
    lines = text.split('\n')
    themes = parse_themes(lines)
    slogans: list[dict] = []
    current_point = ''
    i = 0

    while i < len(lines):
        line = lines[i].rstrip()

        point = POINT_RE.match(line)
        if point:
            current_point = f'{point.group(1).title()}: {point.group(2).strip()}'
            i += 1
            continue

        m = SLOGAN_RE.match(line)
        if not m:
            i += 1
            continue

        number, text_ = int(m.group(1)), m.group(2)
        entry = {
            'number': number,
            'text': text_,
            'icarePhase': '',
            'icarePhaseId': 0,
            'wellnessDomain': '',
            'theme': themes.get(number, ''),
            'point': current_point,
            'condensedCommentary': '',
            'commentary': [],
            'viaStrengths': [],
            'practice': '',
        }
        section = None

        j = i + 1
        while j < len(lines) and not SLOGAN_RE.match(lines[j].rstrip()):
            if POINT_RE.match(lines[j].rstrip()):
                break
            raw = lines[j].rstrip()
            stripped = raw.strip()

            phase = PHASE_RE.match(stripped)
            domain = DOMAIN_RE.match(stripped)
            practice = PRACTICE_RE.match(stripped)

            if phase:
                entry['icarePhase'] = phase.group(1)
                entry['icarePhaseId'] = int(phase.group(2))
            elif domain:
                entry['wellnessDomain'] = domain.group(1)
            elif practice:
                entry['practice'] = practice.group(1)
                section = None
            elif stripped.startswith('**Condensed Commentary:**'):
                section = 'condensed'
            elif stripped.startswith('**Full Commentary:**'):
                section = 'full'
            elif stripped.startswith('**VIA Strengths:**'):
                section = 'via'
            elif stripped in ('---', ''):
                pass
            elif section == 'condensed':
                entry['condensedCommentary'] = (
                    entry['condensedCommentary'] + ' ' + stripped
                ).strip()
            elif section == 'full':
                entry['commentary'].append(stripped)
            elif section == 'via':
                via = VIA_RE.match(stripped)
                if via:
                    entry['viaStrengths'].append(
                        {'strength': via.group(1), 'rationale': via.group(2)}
                    )
            j += 1

        slogans.append(entry)
        i = j

    return slogans


def ts(value) -> str:
    return json.dumps(value, ensure_ascii=False)


def emit(slogans: list[dict]) -> str:
    out = [
        '// GENERATED by scripts/import-slogans.py — do not edit by hand.',
        '// Source: GFA_59_Slogans_Final.md, the master source document for',
        '// Recovering the Mind © 2026 Thomas DeGarmeaux and Grace For Addictions.',
        '// Used within the GFA platform by the author. Attribution must remain',
        '// visible wherever slogans are displayed.',
        '',
        "import type { Slogan } from './types';",
        '',
        'export const SLOGANS: Slogan[] = [',
    ]
    for s in slogans:
        out.append('  {')
        out.append(f'    number: {s["number"]},')
        out.append(f'    text: {ts(s["text"])},')
        out.append(f'    icarePhase: {ts(s["icarePhase"])},')
        out.append(f'    icarePhaseId: {s["icarePhaseId"]},')
        out.append(f'    wellnessDomain: {ts(s["wellnessDomain"])},')
        out.append(f'    theme: {ts(s["theme"])},')
        out.append(f'    point: {ts(s["point"])},')
        out.append(f'    condensedCommentary: {ts(s["condensedCommentary"])},')
        out.append('    commentary: [')
        for c in s['commentary']:
            out.append(f'      {ts(c)},')
        out.append('    ],')
        out.append('    viaStrengths: [')
        for v in s['viaStrengths']:
            out.append(
                f'      {{ strength: {ts(v["strength"])}, rationale: {ts(v["rationale"])} }},'
            )
        out.append('    ],')
        out.append(f'    practice: {ts(s["practice"])},')
        out.append('  },')
    out.append('];')
    out.append('')
    return '\n'.join(out)


def main() -> None:
    slogans = parse(SOURCE.read_text(encoding='utf-8'))

    assert len(slogans) == 59, f'expected 59 slogans, parsed {len(slogans)}'
    assert sorted(s['number'] for s in slogans) == list(range(1, 60)), 'numbering gap'
    for s in slogans:
        n = s['number']
        assert s['icarePhase'], f'slogan {n}: missing ICARE phase'
        assert s['wellnessDomain'], f'slogan {n}: missing wellness domain'
        assert s['condensedCommentary'], f'slogan {n}: missing condensed commentary'
        assert s['commentary'], f'slogan {n}: missing full commentary'
        assert s['practice'], f'slogan {n}: missing practice'
        assert s['viaStrengths'], f'slogan {n}: missing VIA strengths'
        assert s['theme'], f'slogan {n}: missing theme key'

    # The master document states the rebalanced distribution explicitly; hold
    # the import to it so a source edit cannot silently skew the engine.
    from collections import Counter
    dist = Counter(s['icarePhase'] for s in slogans)
    expected = {'Identify': 12, 'Connect': 12, 'Assess': 12, 'Respond': 12, 'Empower': 11}
    assert dist == Counter(expected), f'phase distribution drifted: {dict(dist)}'

    OUT_TS.parent.mkdir(parents=True, exist_ok=True)
    OUT_TS.write_text(emit(slogans), encoding='utf-8')

    words = sum(len(' '.join(s['commentary']).split()) for s in slogans)
    via = sum(len(s['viaStrengths']) for s in slogans)
    print(f'Imported {len(slogans)} slogans → {OUT_TS}')
    print(f'  {words:,} words of full commentary, {via} VIA strength mappings')
    print(f'  phase distribution: {dict(dist)}')


if __name__ == '__main__':
    main()
